spring:
  profiles:
    group:
      "local": "localDB, common"
      "server": "serverDB, common"

    default: "local"
---
spring:
  config:
    activate:
      on-profile: "localDB"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/exchange?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ganadara98

---
spring:
  config:
    activate:
      on-profile: "serverDB"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username: root
    password:  # password ???

---
spring:
  config:
    activate:
      on-profile: "common"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

server:
  error:
    include-exception: false      # Response ? Exception ? ????
    include-message: always       # Response ? Exception Message ? ???? (never | always | on_param)
    include-stacktrace: on_param  # Response ? Stack Trace ? ???? (never | always | on_param) on_trace_params ? deprecated
    whitelabel.enabled: true      # ?? ?? ? Spring ?? ?? ??? ?? ??

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
